config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get 'ask', to: 'pages#ask'
  get 'answer', to: 'pages#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Some documentation for PagesController
class PagesController < ApplicationController
  def ask; end

  def answer
    @question = params[:question]
    @answer = if @question.include? '?'
                'Silly question, get dressed and go to work!'
              elsif @question == 'I am going to work'
                'Great!'
              else
                "I don't care, get dressed and go to work!"
              end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <h1>Stupid Coaching</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/answer.html.erb
<figure>
  <blockquote class="blockquote">
    <p><%= @question %></p>
  </blockquote>
  <figcaption class="blockquote-footer">
    <cite title="Source Title">You</cite>
  </figcaption>
</figure>

<figure style="background-color: #ffffe1;">
  <blockquote class="blockquote">
    <p><strong><%= @answer %></strong></p>
  </blockquote>
  <figcaption class="blockquote-footer">
    <cite title="Source Title">Your coach</cite>
  </figcaption>
</figure>

<div><%= link_to "Ask a new question", ask_url %></div>

app/views/pages/ask.html.erb
<form action="/answer" data-turbo="false">
  <div class="mb-3">
      <label for="inputQuestion" class="form-label">Ask your coach anything:</label>
      <input type="text" name="question" class="form-control" id="inputQuestion" aria-describedby="questionHelp">
      <div id="questionHelp" class="form-text">If I were you I would go to work.</div>
  </div>
    <button type="submit" class="btn btn-primary">Ask!</button>
</form>